### PR TITLE
Feature/refresh changes 3

### PR DESCRIPTION
**Pull request by pinglamb**

### CODE REVIEW

**Comment by krismlek** [comment]
What do you think? @nick-chow

**Comment by pinglamb** [comment]
refresh

**Comment by pinglamb** [comment]
💃

**Comment by pinglamb** [comment]
:mushroom:

**Comment by pinglamb** [comment]
🍄

**Comment by pinglamb** [comment]
🌵

**Comment by pinglamb** [comment]
🍄

**Pull request closed without merging**
